- hosts: [{{host}}]
  sudo: yes
  tasks:
    - shell: echo 'Managed by solar' > /etc/apt/sources.list
      when: {{ensure_other_removed}}
    - shell: wget -qO - {{gpg_key}} | sudo apt-key add -
    - shell: apt-get update
